import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..", "..");

export const componentMapFile = path.join(
  repoRoot,
  "docs",
  "component-library-name-map.md"
);
export const manifestFile = path.join(
  repoRoot,
  "data",
  "micrographics-manifest.json"
);
export const registryFile = path.join(
  repoRoot,
  "src",
  "lib",
  "micrographics",
  "registry.ts"
);

const sourceRoot =
  "docs/Micrographics Vol.1 - Fox Rockett Studio/Components Library/SVG";

function normalizeWhitespace(value) {
  return value.replace(/\s+/g, " ").trim();
}

function parseBatch(line) {
  const match = line.match(/^##\s+Batch\s+(\d+)/);
  return match ? Number(match[1]) : null;
}

function parseComponentRow(line, activeBatch) {
  const match = line.match(
    /^\|\s*Component\s+(\d+)\s*\|\s*`([^`]+)`\s*\|\s*(.+?)\s*\|$/
  );

  if (!match) {
    return null;
  }

  const id = Number(match[1]);

  return {
    id,
    batch: activeBatch ?? 0,
    name: normalizeWhitespace(match[2]),
    summary: normalizeWhitespace(match[3]),
    sourceSvg: `${sourceRoot}/Micrographics Vol.1 - Component ${id}.svg`
  };
}

export function parseComponentMap(markdown) {
  const entries = [];
  let activeBatch = null;

  for (const line of markdown.split(/\r?\n/)) {
    const batch = parseBatch(line);

    if (batch !== null) {
      activeBatch = batch;
      continue;
    }

    const entry = parseComponentRow(line, activeBatch);

    if (entry) {
      entries.push(entry);
    }
  }

  return entries.sort((left, right) => left.id - right.id);
}

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function ensureDirectory(filePath) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
}

function toStatusCounts(entries) {
  return entries.reduce(
    (counts, entry) => {
      counts[entry.status] = (counts[entry.status] ?? 0) + 1;
      return counts;
    },
    {
      mapped: 0,
      claimed: 0,
      "component-ready": 0,
      implemented: 0
    }
  );
}

function escapeForTs(value) {
  return JSON.stringify(value);
}

function buildRegistrySource(entries) {
  const statusCounts = toStatusCounts(entries);

  return `import type { MicrographicSeed } from "@/lib/micrographics/types";

// Auto-generated by \`npm run micro:sync\`.
// Do not edit manually.
export const micrographicSeeds: MicrographicSeed[] = ${JSON.stringify(entries, null, 2)};

export const micrographicStatusCounts = ${JSON.stringify(statusCounts, null, 2)};

export const micrographicSource = ${escapeForTs("docs/component-library-name-map.md")};
`;
}

export function writeRegistry(entries) {
  ensureDirectory(registryFile);
  fs.writeFileSync(registryFile, buildRegistrySource(entries));
}

export function loadManifest() {
  if (!fs.existsSync(manifestFile)) {
    return null;
  }

  return readJson(manifestFile);
}

export function writeManifest(manifest) {
  ensureDirectory(manifestFile);
  fs.writeFileSync(manifestFile, `${JSON.stringify(manifest, null, 2)}\n`);
}

export function syncManifest() {
  const markdown = fs.readFileSync(componentMapFile, "utf8");
  const mappedEntries = parseComponentMap(markdown);
  const previousManifest = loadManifest();
  const previousEntries = new Map(
    (previousManifest?.components ?? []).map((entry) => [entry.id, entry])
  );

  const components = mappedEntries.map((entry) => {
    const previous = previousEntries.get(entry.id);

    return {
      ...entry,
      status: previous?.status ?? "mapped",
      claimedBy: previous?.claimedBy ?? null,
      claimedAt: previous?.claimedAt ?? null,
      componentPath: previous?.componentPath ?? null,
      notes: previous?.notes ?? null
    };
  });

  const manifest = {
    source: "docs/component-library-name-map.md",
    updatedAt: new Date().toISOString(),
    total: components.length,
    components
  };

  writeManifest(manifest);
  writeRegistry(components);

  return manifest;
}

export function readOrSyncManifest() {
  return syncManifest();
}

export function getOption(name, fallback = null) {
  const index = process.argv.indexOf(name);

  if (index === -1) {
    return fallback;
  }

  return process.argv[index + 1] ?? fallback;
}

export function getNumberOption(name, fallback) {
  const value = getOption(name, null);

  if (value === null) {
    return fallback;
  }

  const parsed = Number(value);

  if (!Number.isFinite(parsed) || parsed <= 0) {
    throw new Error(`Invalid value for ${name}: ${value}`);
  }

  return parsed;
}

export function getIdListOption(name) {
  const raw = getOption(name, "");

  if (!raw) {
    return [];
  }

  return raw
    .split(",")
    .map((value) => Number(value.trim()))
    .filter((value) => Number.isFinite(value));
}

export function getActor() {
  return getOption("--by", process.env.CODEX_AGENT ?? os.userInfo().username);
}

export function printEntries(title, entries) {
  console.log(title);

  if (entries.length === 0) {
    console.log("  none");
    return;
  }

  for (const entry of entries) {
    const claimInfo = entry.claimedBy ? ` | by ${entry.claimedBy}` : "";
    console.log(
      `  #${entry.id} [batch ${entry.batch}] ${entry.name} (${entry.status}${claimInfo})`
    );
  }
}

export function updateManifestEntries(manifest, updater) {
  const components = manifest.components.map((entry) => updater({ ...entry }));
  const nextManifest = {
    ...manifest,
    updatedAt: new Date().toISOString(),
    total: components.length,
    components
  };

  writeManifest(nextManifest);
  writeRegistry(components);

  return nextManifest;
}
